// <auto-generated />
using System;
using DotnetCoreORMDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotnetCoreORMDemo.Migrations
{
    [DbContext(typeof(CustomerManagementContext))]
    partial class CustomerManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotnetCoreORMDemo.Models.Customer", b =>
                {
                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DotnetCoreORMDemo.Models.Order", b =>
                {
                    b.Property<int>("orderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("customerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("employeeID")
                        .HasColumnType("int");

                    b.Property<decimal?>("freight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("requiredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("shipAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shipCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shipCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shipPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shipRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("shipVia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("shippedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("orderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DotnetCoreORMDemo.Models.WritableRow", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("WritableRows");
                });
#pragma warning restore 612, 618
        }
    }
}
